name: Build OpenWrt
#------------------#
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '25.12.5'
        type: choice
        options:
          - '25.12.5'
          - '25.12.6'
          - '25.12.7'
          - '25.12.8'
          - '25.12.9'
      devices:
        description: 'Devices'
        required: true
        default: 'wr30u'
        type: choice
        options:
          - 'wr30u'
          - 'hc5962'
          - 'neo2'
          - 'x64'
#------------------#
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CONF_FILE1: main/${{ inputs.devices }}/${{ inputs.devices }}.config
      CONF_FILE2: main/${{ inputs.devices }}/99-custom
      CONF_FILE3: main/${{ inputs.devices }}/mt7981b-xiaomi-mi-router-wr30u-ubootmod.dts
    steps:
#-----------------------------------------------#
    - name: Initialization environment
      run: |
        sudo -E apt -qqy update
        sudo -E apt -qqy install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
#-----------------------------------------------#
    - name: Checkout main
      uses: actions/checkout@v5
      with:
        path: main

    - name: Checkout openwrt
      uses: actions/checkout@v5
      with:
        repository: openwrt/openwrt
        ref: v${{ inputs.version }}
        path: openwrt
#-----------------------------------------------#
    - name: Update Install feeds
      run: |
        cd openwrt
        echo 'src-git rtp2httpd https://github.com/stackia/rtp2httpd.git' >>feeds.conf.default
        echo 'src-git taskplan https://github.com/sirpdboy/luci-app-ddns-go.git' >>feeds.conf.default
        echo 'src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main' >>feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
#-----------------------------------------------#
    - name: Load custom env
      run: |
        if [ "${{ inputs.devices }}" == "wr30u" ]; then
          echo "MK_TARGET=mediatek/filogic" >> $GITHUB_ENV
        elif [ "${{ inputs.devices }}" == "hc5962" ]; then
          echo "MK_TARGET=ramips/mt7621" >> $GITHUB_ENV
        elif [ "${{ inputs.devices }}" == "neo2" ]; then
          echo "MK_TARGET=sunxi/cortexa53" >> $GITHUB_ENV
          sed -i 's|ucidef_set_interface_lan \"eth0\"|ucidef_set_interface_wan \"eth0\"|g' openwrt/target/linux/sunxi/base-files/etc/board.d/02_network
        elif [ "${{ inputs.devices }}" == "x64" ]; then
          echo "MK_TARGET=x86/64" >> $GITHUB_ENV
        fi
#-----------------------------------------------#
    - name: Load custom configuration
      run: |
        if [ -e "${{ env.CONF_FILE1 }}" ]; then
          cp "${{ env.CONF_FILE1 }}" openwrt/.config
        fi

        if [ -e "${{ env.CONF_FILE2 }}" ]; then
          mkdir -p openwrt/files/etc/uci-defaults
          cp "${{ env.CONF_FILE2 }}" openwrt/files/etc/uci-defaults/
        fi

        if [ -e "${{ env.CONF_FILE3 }}" ]; then
          cp -f "${{ env.CONF_FILE3 }}" openwrt/target/linux/mediatek/dts/
        fi

        API_URL=https://downloads.openwrt.org/releases/${{ inputs.version }}/targets/${MK_TARGET}/openwrt-${{ inputs.version }}-${MK_TARGET//\//-}.manifest
        echo "Fetching: $API_URL"
        HASH=$(curl -s "$API_URL" | grep "^kernel - " | sed -n 's/.*~\([a-f0-9]\{32\}\)-r.*/\1/p')
        echo "Fetching: $HASH"

        if [ -n "$HASH" ]; then
          sed -i "s|grep.*vermagic|echo $HASH > \$(LINUX_DIR)/.vermagic|g" openwrt/include/kernel-defaults.mk
        fi
#-----------------------------------------------#
    - name: Download package
      run: |
        cd openwrt
        make defconfig
        make download -j8
#-----------------------------------------------#
    - name: Make the firmware
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s
        rm -rf bin/targets/${{ env.MK_TARGET }}/packages
#-----------------------------------------------#
    - name: Upload firmware directory
      uses: actions/upload-artifact@v6
      with:
        name: OpenWrt_${{ inputs.version }}_${{ inputs.devices }}_${{ github.sha }}
        path: openwrt/bin/targets/${{ env.MK_TARGET }}
#-----------------------------------------------#
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: OpenWrt_${{ inputs.version }}_${{ inputs.devices }}_${{ github.sha }}
        files: openwrt/bin/targets/${{ env.MK_TARGET }}/*
#-----------------------------------------------#
